const CHANGE_THEME: string = 'CHANGE_THEME';

const FETCH_VEHICLES: string = 'FETCH_VEHICLES';
const FETCH_VEHICLES_SUCCESS: string = 'FETCH_VEHICLES_SUCCESS';
const FETCH_VEHICLES_FAILURE: string = 'FETCH_VEHICLES_FAILURE';
const SET_VEHICLES_PAGE: string = 'SET_VEHICLES_PAGE';
const SET_VEHICLES_FILTER: string = 'SET_VEHICLES_FILTER';

export {
  CHANGE_THEME,
  FETCH_VEHICLES,
  FETCH_VEHICLES_SUCCESS,
  FETCH_VEHICLES_FAILURE,
  SET_VEHICLES_PAGE,
  SET_VEHICLES_FILTER
}